#!/usr/bin/env bash

echo "Enter the URL of the repository you want to clone: "
read -r url

repository=$(echo $(echo $url|cut -d '/' -f5)|cut -d '.' -f1)

check_answer() {
  while [[ "$choice" != "YES" && "$choice" !=  "NO" ]]; do
    echo "That was not one of your choices. Please choose YES or NO."
    read -r choice
  done
}

if [ -e ~/$repository ]; then
  echo "The repository already exists. Do you want to pull the repository? YES or NO"
  read -r choice
  # Call the function
  check_answer
	# Pulling works, you have to be in the repository to be able to pull it.
  if [[ "$choice" == "YES" ]]; then
          echo "You chose to pull the repository."
          cd
          cd $repository
          git pull $url
  else
          echo "You chose to NOT pull the repository. See you later!"
  fi
else
  echo "The repository doesn't exist. Do you want to clone the repository? YES or NO"
  read -r choice
  # Call the function
  check_answer
  # Cloning works
  if [[ "$choice" == "YES" ]]; then
          echo "You chose to clone the repository."
          cd
          git clone $url
  else
          echo "You chose to NOT clone the repository. See you later!"
  fi
fi
